



@Entity
@Table(name = "episode")
public class EpisodeShell {
	
	// Id means the field is the primary key
	// Column allows you to set the SQL column name to something other than the default generated by Hibernate
	@Id
	@Column(name = "id")
	private String episode_id;
	@Column(name = "master_episode_id")
	private String master_episode_id;
	@Column(name = "member_id")
	private String member_id;
	@Column(name = "claim_id")
	private String claim_id;
	private transient ClaimServLine claim;
	@Column(name = "episode_type")
	private String episode_type;
	@Column(name = "trigger_begin_date")
	private Date trig_begin_date;
	@Column(name = "trigger_end_date")
	private Date trig_end_date;
	@Column(name = "episode_begin_date")
	private Date episode_begin_date;
	@Column(name = "episode_end_date")
	private Date episode_end_date;
	private int look_back;
	private String look_ahead;
	private boolean req_conf_claim;
	private String conf_claim_id;
	@Transient
	private transient ClaimServLine conf_claim;
	private String min_code_separation;
	private String max_code_separation;
	private String trig_by_episode_id;
	private String trig_by_master_episode_id;
	private boolean trig_by_episode;

	

	private String dxPassCode;
	private String pxPassCode;
	private String emPassCode;
	
	private String conf_dxPassCode;
	private String conf_pxPassCode;
	private String conf_emPassCode;
	
	// if the episode doesn't survive resolution, dropped=true
	private boolean dropped;
	// this is the claim of the triggered episode that causes the drop
	private String win_claim_id;
	// if this is Procedural and has been truncated, that is indicated here (win_claim_id will be the truncating claim)
	private String win_master_episode_id;
	

	private boolean truncated;
	// these are the original dates before truncation
	private Date orig_episode_begin_date;
	private Date orig_episode_end_date;
	
	private ArrayList<AssignedClaim> assigned_claims;
	
	private boolean isAssociated; // true ONLY if a final leveling association has been made for this episode (even at top level)
	private int AssociatedLevel; // should be 1 unless isAssociated is true;
	private int AssociationCount; // number of times the episode has been associated, default 0

	private ArrayList<AssociatedEpisode> potentially_associated_episodes;
	
	private ArrayList<AssociatedEpisode> potentially_associated_parent_episodes;
	
	private HashMap<String, ArrayList<AssociatedEpisode>> associated_episodes;
	
	String attr_cost_physician_id;
	String attr_cost_facility_id;
	String attr_visit_physician_id;
	String attr_visit_facility_id;
	
	/* New attribution variables... */
	String attr_trigger_physician_id;
	String attr_trigger_facility_id;
	String attr_trig_cost_physician_id;
	String attr_trig_cost_facility_id;

	/*
	private BigDecimal assignedDollarsSplit;
	private BigDecimal assignedDollarsUnsplit;
	private BigDecimal assignedDollarsSplit_T;
	private BigDecimal assignedDollarsSplit_C;
	private BigDecimal assignedDollarsSplit_TC;
	private BigDecimal assignedDollarsUnsplit_T;
	private BigDecimal assignedDollarsUnsplit_C;
	private BigDecimal assignedDollarsUnsplit_TC;
	
	private BigDecimal assignedDollarsSplit_IP;
	private BigDecimal assignedDollarsUnsplit_IP;
	private BigDecimal assignedDollarsSplit_IP_T;
	private BigDecimal assignedDollarsSplit_IP_C;
	private BigDecimal assignedDollarsSplit_IP_TC;
	private BigDecimal assignedDollarsUnsplit_IP_T;
	private BigDecimal assignedDollarsUnsplit_IP_C;
	private BigDecimal assignedDollarsUnsplit_IP_TC;
	
	private BigDecimal assignedDollarsSplit_OP;
	private BigDecimal assignedDollarsUnsplit_OP;
	private BigDecimal assignedDollarsSplit_OP_T;
	private BigDecimal assignedDollarsSplit_OP_C;
	private BigDecimal assignedDollarsSplit_OP_TC;
	private BigDecimal assignedDollarsUnsplit_OP_T;
	private BigDecimal assignedDollarsUnsplit_OP_C;
	private BigDecimal assignedDollarsUnsplit_OP_TC;
	
	private BigDecimal assignedDollarsSplit_PB;
	private BigDecimal assignedDollarsUnsplit_PB;
	private BigDecimal assignedDollarsSplit_PB_T;
	private BigDecimal assignedDollarsSplit_PB_C;
	private BigDecimal assignedDollarsSplit_PB_TC;
	private BigDecimal assignedDollarsUnsplit_PB_T;
	private BigDecimal assignedDollarsUnsplit_PB_C;
	private BigDecimal assignedDollarsUnsplit_PB_TC;
	
	private BigDecimal assignedDollarsSplit_RX;
	private BigDecimal assignedDollarsUnsplit_RX;
	private BigDecimal assignedDollarsSplit_RX_T;
	private BigDecimal assignedDollarsSplit_RX_C;
	private BigDecimal assignedDollarsUnsplit_RX_T;
	private BigDecimal assignedDollarsUnsplit_RX_C;
	
	private BigDecimal associatedDollarsSplit;
	private BigDecimal associatedDollarsUnsplit;
	private BigDecimal associatedDollarsSplit_T;
	private BigDecimal associatedDollarsSplit_C;
	private BigDecimal associatedDollarsUnsplit_T;
	private BigDecimal associatedDollarsUnsplit_C;
	
	private BigDecimal associatedDollarsSplit_IP;
	private BigDecimal associatedDollarsUnsplit_IP;
	private BigDecimal associatedDollarsSplit_IP_T;
	private BigDecimal associatedDollarsSplit_IP_C;
	private BigDecimal associatedDollarsUnsplit_IP_T;
	private BigDecimal associatedDollarsUnsplit_IP_C;
	
	private BigDecimal associatedDollarsSplit_OP;
	private BigDecimal associatedDollarsUnsplit_OP;
	private BigDecimal associatedDollarsSplit_OP_T;
	private BigDecimal associatedDollarsSplit_OP_C;
	private BigDecimal associatedDollarsUnsplit_OP_T;
	private BigDecimal associatedDollarsUnsplit_OP_C;
	
	private BigDecimal associatedDollarsSplit_PB;
	private BigDecimal associatedDollarsUnsplit_PB;
	private BigDecimal associatedDollarsSplit_PB_T;
	private BigDecimal associatedDollarsSplit_PB_C;
	private BigDecimal associatedDollarsUnsplit_PB_T;
	private BigDecimal associatedDollarsUnsplit_PB_C;
	
	private BigDecimal associatedDollarsSplit_RX;
	private BigDecimal associatedDollarsUnsplit_RX;
	private BigDecimal associatedDollarsSplit_RX_T;
	private BigDecimal associatedDollarsSplit_RX_C;
	private BigDecimal associatedDollarsUnsplit_RX_T;
	private BigDecimal associatedDollarsUnsplit_RX_C;
*/
	// the transient annotation means you don't want to map this field to a column
	@Transient
	private HashMap<String, HashMap<String, HashMap<String, BigDecimal>>> associatedDollarsByLevel;
	// <level, <claim type <dollar type, amount>
	// level is level of association
	// claim type is IP/OP/PB/RX or CL for not split by type
	// dollar type is: 
	/*
	associatedDollarsSplit
	associatedDollarsUnSplit
	associateddollarsSplit_T
	associateddollarsSplit_C
	associatedDollarsUnsplit_T
	associatedDollarsUnsplit_C
	*/
	public EpisodeShell () {
		assigned_claims = new ArrayList<AssignedClaim>();
		potentially_associated_episodes = new ArrayList<AssociatedEpisode>();
		potentially_associated_parent_episodes = new ArrayList<AssociatedEpisode>();
		associated_episodes = new HashMap<String, ArrayList<AssociatedEpisode>>();
		isAssociated=false;
		AssociatedLevel = 1;
		AssociationCount = 0;
		/*
		assignedDollarsSplit = new BigDecimal("0");
		assignedDollarsUnsplit = new BigDecimal("0");
		assignedDollarsSplit_T = new BigDecimal("0");
		assignedDollarsSplit_TC = new BigDecimal("0");
		assignedDollarsSplit_C = new BigDecimal("0");
		assignedDollarsUnsplit_T = new BigDecimal("0");
		assignedDollarsUnsplit_TC = new BigDecimal("0");
		assignedDollarsUnsplit_C = new BigDecimal("0");
		
		assignedDollarsSplit_IP = new BigDecimal("0");
		assignedDollarsUnsplit_IP = new BigDecimal("0");
		assignedDollarsSplit_IP_T = new BigDecimal("0");
		assignedDollarsSplit_IP_TC = new BigDecimal("0");
		assignedDollarsSplit_IP_C = new BigDecimal("0");
		assignedDollarsUnsplit_IP_T = new BigDecimal("0");
		assignedDollarsUnsplit_IP_TC = new BigDecimal("0");
		assignedDollarsUnsplit_IP_C = new BigDecimal("0");
		
		assignedDollarsSplit_OP = new BigDecimal("0");
		assignedDollarsUnsplit_OP = new BigDecimal("0");
		assignedDollarsSplit_OP_T = new BigDecimal("0");
		assignedDollarsSplit_OP_TC = new BigDecimal("0");
		assignedDollarsSplit_OP_C = new BigDecimal("0");
		assignedDollarsUnsplit_OP_T = new BigDecimal("0");
		assignedDollarsUnsplit_OP_TC = new BigDecimal("0");
		assignedDollarsUnsplit_OP_C = new BigDecimal("0");
		
		assignedDollarsSplit_PB = new BigDecimal("0");
		assignedDollarsUnsplit_PB = new BigDecimal("0");
		assignedDollarsSplit_PB_T = new BigDecimal("0");
		assignedDollarsSplit_PB_TC = new BigDecimal("0");
		assignedDollarsSplit_PB_C = new BigDecimal("0");
		assignedDollarsUnsplit_PB_T = new BigDecimal("0");
		assignedDollarsUnsplit_PB_TC = new BigDecimal("0");
		assignedDollarsUnsplit_PB_C = new BigDecimal("0");
		
		assignedDollarsSplit_RX = new BigDecimal("0");
		assignedDollarsUnsplit_RX = new BigDecimal("0");
		assignedDollarsSplit_RX_T = new BigDecimal("0");
		assignedDollarsSplit_RX_C = new BigDecimal("0");
		assignedDollarsUnsplit_RX_T = new BigDecimal("0");
		assignedDollarsUnsplit_RX_C = new BigDecimal("0");
		
		associatedDollarsSplit = new BigDecimal("0");
		associatedDollarsUnsplit = new BigDecimal("0");
		associatedDollarsSplit_T = new BigDecimal("0");
		associatedDollarsSplit_C = new BigDecimal("0");
		associatedDollarsUnsplit_T = new BigDecimal("0");
		associatedDollarsUnsplit_C = new BigDecimal("0");
		
		associatedDollarsSplit_IP = new BigDecimal("0");
		associatedDollarsUnsplit_IP = new BigDecimal("0");
		associatedDollarsSplit_IP_T = new BigDecimal("0");
		associatedDollarsSplit_IP_C = new BigDecimal("0");
		associatedDollarsUnsplit_IP_T = new BigDecimal("0");
		associatedDollarsUnsplit_IP_C = new BigDecimal("0");
		
		associatedDollarsSplit_OP = new BigDecimal("0");
		associatedDollarsUnsplit_OP = new BigDecimal("0");
		associatedDollarsSplit_OP_T = new BigDecimal("0");
		associatedDollarsSplit_OP_C = new BigDecimal("0");
		associatedDollarsUnsplit_OP_T = new BigDecimal("0");
		associatedDollarsUnsplit_OP_C = new BigDecimal("0");
		
		associatedDollarsSplit_PB = new BigDecimal("0");
		associatedDollarsUnsplit_PB = new BigDecimal("0");
		associatedDollarsSplit_PB_T = new BigDecimal("0");
		associatedDollarsSplit_PB_C = new BigDecimal("0");
		associatedDollarsUnsplit_PB_T = new BigDecimal("0");
		associatedDollarsUnsplit_PB_C = new BigDecimal("0");
		
		associatedDollarsSplit_RX = new BigDecimal("0");
		associatedDollarsUnsplit_RX = new BigDecimal("0");
		associatedDollarsSplit_RX_T = new BigDecimal("0");
		associatedDollarsSplit_RX_C = new BigDecimal("0");
		associatedDollarsUnsplit_RX_T = new BigDecimal("0");
		associatedDollarsUnsplit_RX_C = new BigDecimal("0");
		*/
		
		associatedDollarsByLevel = new HashMap<String, HashMap<String, HashMap<String, BigDecimal>>>();
		
		for (int i=1; i<6; i++) {
			String si = "" + i;
			
			HashMap<String, BigDecimal> tmpMap = new HashMap<String, BigDecimal>();
			HashMap<String, BigDecimal> tmpMapCL = new HashMap<String, BigDecimal>();
			HashMap<String, BigDecimal> tmpMapIP = new HashMap<String, BigDecimal>();
			HashMap<String, BigDecimal> tmpMapOP = new HashMap<String, BigDecimal>();
			HashMap<String, BigDecimal> tmpMapPB = new HashMap<String, BigDecimal>();
			HashMap<String, BigDecimal> tmpMapRX = new HashMap<String, BigDecimal>();
			HashMap<String, HashMap<String, BigDecimal>> tmpLgMap = new HashMap<String, HashMap<String, BigDecimal>>();
			BigDecimal tmpBD = new BigDecimal("0");
			tmpBD.setScale(10, BigDecimal.ROUND_HALF_EVEN);
			
			
			tmpMap.put("associatedDollarsSplit", tmpBD);
			tmpMap.put("associatedDollarsUnsplit", tmpBD);
			tmpMap.put("associatedDollarsSplit_T", tmpBD);
			tmpMap.put("associatedDollarsSplit_C", tmpBD);
			tmpMap.put("associatedDollarsSplit_TC", tmpBD);
			tmpMap.put("associatedDollarsUnsplit_T", tmpBD);
			tmpMap.put("associatedDollarsUnsplit_C", tmpBD);
			tmpMap.put("associatedDollarsUnsplit_TC", tmpBD);
			
			tmpMapCL.put("associatedDollarsSplit", tmpBD);
			tmpMapCL.put("associatedDollarsUnsplit", tmpBD);
			tmpMapCL.put("associatedDollarsSplit_T", tmpBD);
			tmpMapCL.put("associatedDollarsSplit_C", tmpBD);
			tmpMapCL.put("associatedDollarsSplit_TC", tmpBD);
			tmpMapCL.put("associatedDollarsUnsplit_T", tmpBD);
			tmpMapCL.put("associatedDollarsUnsplit_C", tmpBD);
			tmpMapCL.put("associatedDollarsUnsplit_TC", tmpBD);
			
			tmpMapIP.put("associatedDollarsSplit", tmpBD);
			tmpMapIP.put("associatedDollarsUnsplit", tmpBD);
			tmpMapIP.put("associatedDollarsSplit_T", tmpBD);
			tmpMapIP.put("associatedDollarsSplit_C", tmpBD);
			tmpMapIP.put("associatedDollarsSplit_TC", tmpBD);
			tmpMapIP.put("associatedDollarsUnsplit_T", tmpBD);
			tmpMapIP.put("associatedDollarsUnsplit_C", tmpBD);
			tmpMapIP.put("associatedDollarsUnsplit_TC", tmpBD);
			
			tmpMapOP.put("associatedDollarsSplit", tmpBD);
			tmpMapOP.put("associatedDollarsUnsplit", tmpBD);
			tmpMapOP.put("associatedDollarsSplit_T", tmpBD);
			tmpMapOP.put("associatedDollarsSplit_C", tmpBD);
			tmpMapOP.put("associatedDollarsSplit_TC", tmpBD);
			tmpMapOP.put("associatedDollarsUnsplit_T", tmpBD);
			tmpMapOP.put("associatedDollarsUnsplit_C", tmpBD);
			tmpMapOP.put("associatedDollarsUnsplit_TC", tmpBD);
			
			tmpMapPB.put("associatedDollarsSplit", tmpBD);
			tmpMapPB.put("associatedDollarsUnsplit", tmpBD);
			tmpMapPB.put("associatedDollarsSplit_T", tmpBD);
			tmpMapPB.put("associatedDollarsSplit_C", tmpBD);
			tmpMapPB.put("associatedDollarsSplit_TC", tmpBD);
			tmpMapPB.put("associatedDollarsUnsplit_T", tmpBD);
			tmpMapPB.put("associatedDollarsUnsplit_C", tmpBD);
			tmpMapPB.put("associatedDollarsUnsplit_TC", tmpBD);
			
			tmpMapCL.put("associatedDollarsSplit", tmpBD);
			tmpMapCL.put("associatedDollarsUnsplit", tmpBD);
			tmpMapCL.put("associatedDollarsSplit_T", tmpBD);
			tmpMapCL.put("associatedDollarsSplit_C", tmpBD);
			tmpMapCL.put("associatedDollarsSplit_TC", tmpBD);
			tmpMapCL.put("associatedDollarsUnsplit_T", tmpBD);
			tmpMapCL.put("associatedDollarsUnsplit_C", tmpBD);
			tmpMapCL.put("associatedDollarsUnsplit_TC", tmpBD);
			
			tmpMapRX.put("associatedDollarsSplit", tmpBD);
			tmpMapRX.put("associatedDollarsUnsplit", tmpBD);
			tmpMapRX.put("associatedDollarsSplit_T", tmpBD);
			tmpMapRX.put("associatedDollarsSplit_C", tmpBD);
			tmpMapRX.put("associatedDollarsSplit_TC", tmpBD);
			tmpMapRX.put("associatedDollarsUnsplit_T", tmpBD);
			tmpMapRX.put("associatedDollarsUnsplit_C", tmpBD);
			tmpMapRX.put("associatedDollarsUnsplit_TC", tmpBD);
			
			tmpLgMap.put("CL", tmpMapCL);
			tmpLgMap.put("IP", tmpMapIP);
			tmpLgMap.put("OP", tmpMapOP);
			tmpLgMap.put("PB", tmpMapPB);
			tmpLgMap.put("RX", tmpMapRX);
			
			associatedDollarsByLevel.put(si, tmpLgMap);
			
			//associatedDollarsByLevel.get(si).putAll(tmpLgMap);
			
			
			
			
		}
		
	}
	
	

	public String getEpisode_id() {
		return episode_id;
	}
	public void setEpisode_id(String episode_id) {
		this.episode_id = episode_id;
		this.setMaster_episode_id(this.getEpisode_id() + 
				( this.getClaim() == null  ?  "" : "_" +  this.getClaim().getClaim_line_id()) );
				//this.setMaster_claim_id(this.getClaim_id() + "_" + this.getClaim_line_id());
	}
	public String getMaster_episode_id() {
		return master_episode_id;
	}
	public void setMaster_episode_id(String master_episode_id) {
		this.master_episode_id = master_episode_id;
	}
	public String getMember_id() {
		return member_id;
	}
	public void setMember_id(String member_id) {
		this.member_id = member_id;
	}
	public String getClaim_id() {
		return claim_id;
	}
	public void setClaim_id(String claim_id) {
		this.claim_id = claim_id;
	}
	public Date getTrig_begin_date() {
		return trig_begin_date;
	}
	public void setTrig_begin_date(Date trig_begin_date) {
		this.trig_begin_date = trig_begin_date;
	}
	public Date getTrig_end_date() {
		return trig_end_date;
	}
	public void setTrig_end_date(Date trig_end_date) {
		this.trig_end_date = trig_end_date;
	}
	public Date getEpisode_begin_date() {
		return episode_begin_date;
	}
	public void setEpisode_begin_date(Date episode_begin_date) {
		this.episode_begin_date = episode_begin_date;
	}
	public Date getEpisode_end_date() {
		return episode_end_date;
	}
	public void setEpisode_end_date(Date episode_end_date) {
		this.episode_end_date = episode_end_date;
	}
	public int getLook_back() {
		return look_back;
	}
	public void setLook_back(int look_back) {
		this.look_back = look_back;
	}
	public String getLook_ahead() {
		return look_ahead;
	}
	public void setLook_ahead(String look_ahead) {
		this.look_ahead = look_ahead;
	}
	public boolean isReq_conf_claim() {
		return req_conf_claim;
	}
	public void setReq_conf_claim(boolean req_conf_claim) {
		this.req_conf_claim = req_conf_claim;
	}
	public String getConf_claim_id() {
		return conf_claim_id;
	}
	public void setConf_claim_id(String conf_claim_id) {
		this.conf_claim_id = conf_claim_id;
	}
	public String getMin_code_separation() {
		return min_code_separation;
	}
	public void setMin_code_separation(String min_code_separation) {
		this.min_code_separation = min_code_separation;
	}
	public String getMax_code_separation() {
		return max_code_separation;
	}
	public void setMax_code_separation(String max_code_separation) {
		this.max_code_separation = max_code_separation;
	}
	public String getTrig_by_episode_id() {
		return trig_by_episode_id;
	}
	public void setTrig_by_episode_id(String trig_by_episode_id) {
		this.trig_by_episode_id = trig_by_episode_id;
	}
	public String getTrig_by_master_episode_id() {
		return trig_by_master_episode_id;
	}
	public void setTrig_by_master_episode_id(String trig_by_master_episode_id) {
		this.trig_by_master_episode_id = trig_by_master_episode_id;
	}
	public boolean isTrig_by_episode() {
		return trig_by_episode;
	}
	public void setTrig_by_episode(boolean trig_by_episode) {
		this.trig_by_episode = trig_by_episode;
	}
	public ClaimServLine getClaim() {
		return claim;
	}
	public void setClaim(ClaimServLine claim) {
		this.claim = claim;
	}

	public ClaimServLine getConf_claim() {
		return conf_claim;
	}

	public void setConf_claim(ClaimServLine conf_claim) {
		this.conf_claim = conf_claim;
	}

	public String getDxPassCode() {
		return dxPassCode;
	}

	public void setDxPassCode(String dxPassCode) {
		this.dxPassCode = dxPassCode;
	}

	public String getPxPassCode() {
		return pxPassCode;
	}

	public void setPxPassCode(String pxPassCode) {
		this.pxPassCode = pxPassCode;
	}

	public String getEmPassCode() {
		return emPassCode;
	}

	public void setEmPassCode(String emPassCode) {
		this.emPassCode = emPassCode;
	}

	public String getConf_dxPassCode() {
		return conf_dxPassCode;
	}

	public void setConf_dxPassCode(String conf_dxPassCode) {
		this.conf_dxPassCode = conf_dxPassCode;
	}

	public String getConf_pxPassCode() {
		return conf_pxPassCode;
	}

	public void setConf_pxPassCode(String conf_pxPassCode) {
		this.conf_pxPassCode = conf_pxPassCode;
	}

	public String getConf_emPassCode() {
		return conf_emPassCode;
	}

	public void setConf_emPassCode(String conf_emPassCode) {
		this.conf_emPassCode = conf_emPassCode;
	}
	public String getEpisode_type() {
		return episode_type;
	}
	public void setEpisode_type(String episode_type) {
		this.episode_type = episode_type;
	}
	
	public boolean isDropped() {
		return dropped;
	}

	public void setDropped(boolean dropped) {
		this.dropped = dropped;
	}

	public String getWin_claim_id() {
		return win_claim_id;
	}

	public void setWin_claim_id(String win_claim_id) {
		this.win_claim_id = win_claim_id;
	}
	
	public String getWin_master_episode_id() {
		return win_master_episode_id;
	}
	
	public void setWin_master_episode_id(String win_master_episode_id) {
		this.win_master_episode_id = win_master_episode_id;
	}

	public boolean isTruncated() {
		return truncated;
	}

	public void setTruncated(boolean truncated) {
		this.truncated = truncated;
	}

	public Date getOrig_episode_begin_date() {
		return orig_episode_begin_date;
	}

	public void setOrig_episode_begin_date(Date orig_episode_begin_date) {
		this.orig_episode_begin_date = orig_episode_begin_date;
	}

	public Date getOrig_episode_end_date() {
		return orig_episode_end_date;
	}

	public void setOrig_episode_end_date(Date orig_episode_end_date) {
		this.orig_episode_end_date = orig_episode_end_date;
	}
	
	public ArrayList<AssignedClaim> getAssigned_claims() {
		return assigned_claims;
	}

	public void setAssigned_claims(ArrayList<AssignedClaim> assigned_claims) {
		this.assigned_claims = assigned_claims;
	}
	
	public boolean isAssociated() {
		return isAssociated;
	}

	public void setAssociated(boolean isAssociated) {
		this.isAssociated = isAssociated;
	}
	
	public int getAssociatedLevel() {
		return AssociatedLevel;
	}

	public void setAssociatedLevel(int associatedLevel) {
		AssociatedLevel = associatedLevel;
	}
	
	public int getAssociationCount() {
		return AssociationCount;
	}

	public void setAssociationCount(int associationCount) {
		AssociationCount = associationCount;
	}
	
	public String getAttr_cost_physician_id() {
		return attr_cost_physician_id;
	}

	public void setAttr_cost_physician_id(String attr_cost_physician_id) {
		this.attr_cost_physician_id = attr_cost_physician_id;
	}

	public String getAttr_cost_facility_id() {
		return attr_cost_facility_id;
	}

	public void setAttr_cost_facility_id(String attr_cost_facility_id) {
		this.attr_cost_facility_id = attr_cost_facility_id;
	}

	public String getAttr_visit_physician_id() {
		return attr_visit_physician_id;
	}

	public void setAttr_visit_physician_id(String attr_visit_physician_id) {
		this.attr_visit_physician_id = attr_visit_physician_id;
	}

	public String getAttr_visit_facility_id() {
		return attr_visit_facility_id;
	}

	public void setAttr_visit_facility_id(String attr_visit_facility_id) {
		this.attr_visit_facility_id = attr_visit_facility_id;
	}
	
	public String getAttr_trigger_physician_id() {
		return attr_trigger_physician_id;
	}

	public void setAttr_trigger_physician_id(String attr_trigger_physician_id) {
		this.attr_trigger_physician_id = attr_trigger_physician_id;
	}

	public String getAttr_trigger_facility_id() {
		return attr_trigger_facility_id;
	}

	public void setAttr_trigger_facility_id(String attr_trigger_facility_id) {
		this.attr_trigger_facility_id = attr_trigger_facility_id;
	}

	public String getAttr_trig_cost_physician_id() {
		return attr_trig_cost_physician_id;
	}

	public void setAttr_trig_cost_physician_id(String attr_trig_cost_physician_id) {
		this.attr_trig_cost_physician_id = attr_trig_cost_physician_id;
	}

	public String getAttr_trig_cost_facility_id() {
		return attr_trig_cost_facility_id;
	}

	public void setAttr_trig_cost_facility_id(String attr_trig_cost_facility_id) {
		this.attr_trig_cost_facility_id = attr_trig_cost_facility_id;
	}

	public ArrayList<AssociatedEpisode> getPotentially_associated_episodes() {
		return potentially_associated_episodes;
	}

	public void setPotentially_associated_parent_episodes(
			ArrayList<AssociatedEpisode> potentially_associated_parent_episodes) {
		this.potentially_associated_episodes = potentially_associated_parent_episodes;
	}
	
	public ArrayList<AssociatedEpisode> getPotentially_associated_parent_episodes() {
		return potentially_associated_parent_episodes;
	}

	public void setPotentially_associated_episodes(
			ArrayList<AssociatedEpisode> potentially_associated_episodes) {
		this.potentially_associated_episodes = potentially_associated_episodes;
	}

	public HashMap<String, ArrayList<AssociatedEpisode>> getAssociated_episodes() {
		return associated_episodes;
	}

	public void setAssociated_episodes(
			HashMap<String, ArrayList<AssociatedEpisode>> associated_episodes) {
		this.associated_episodes = associated_episodes;
	}

/*
	public BigDecimal getAssignedDollarsSplit() {
		return assignedDollarsSplit;
	}

	public void setAssignedDollarsSplit(BigDecimal assignedDollarsSplit) {
		this.assignedDollarsSplit = assignedDollarsSplit;
	}
	
	public BigDecimal getAssignedDollarsUnsplit() {
		return assignedDollarsUnsplit;
	}

	public void setAssignedDollarsUnsplit(BigDecimal assignedDollarsUnsplit) {
		this.assignedDollarsUnsplit = assignedDollarsUnsplit;
	}
	
	public BigDecimal getAssociatedDollarsSplit() {
		return associatedDollarsSplit;
	}

	public void setAssociatedDollarsSplit(BigDecimal associatedDollarsSplit) {
		this.associatedDollarsSplit = associatedDollarsSplit;
	}

	public BigDecimal getAssociatedDollarsUnsplit() {
		return associatedDollarsUnsplit;
	}

	public void setAssociatedDollarsUnsplit(BigDecimal associatedDollarsUnsplit) {
		this.associatedDollarsUnsplit = associatedDollarsUnsplit;
	}
	
	public BigDecimal getAssignedDollarsSplit_T() {
		return assignedDollarsSplit_T;
	}

	public void setAssignedDollarsSplit_T(BigDecimal assignedDollarsSplit_T) {
		this.assignedDollarsSplit_T = assignedDollarsSplit_T;
	}

	public BigDecimal getAssignedDollarsSplit_C() {
		return assignedDollarsSplit_C;
	}

	public void setAssignedDollarsSplit_C(BigDecimal assignedDollarsSplit_C) {
		this.assignedDollarsSplit_C = assignedDollarsSplit_C;
	}

	public BigDecimal getAssignedDollarsSplit_TC() {
		return assignedDollarsSplit_TC;
	}

	public void setAssignedDollarsSplit_TC(BigDecimal assignedDollarsSplit_TC) {
		this.assignedDollarsSplit_TC = assignedDollarsSplit_TC;
	}

	public BigDecimal getAssignedDollarsUnsplit_T() {
		return assignedDollarsUnsplit_T;
	}

	public void setAssignedDollarsUnsplit_T(BigDecimal assignedDollarsUnsplit_T) {
		this.assignedDollarsUnsplit_T = assignedDollarsUnsplit_T;
	}

	public BigDecimal getAssignedDollarsUnsplit_C() {
		return assignedDollarsUnsplit_C;
	}

	public void setAssignedDollarsUnsplit_C(BigDecimal assignedDollarsUnsplit_C) {
		this.assignedDollarsUnsplit_C = assignedDollarsUnsplit_C;
	}

	public BigDecimal getAssignedDollarsUnsplit_TC() {
		return assignedDollarsUnsplit_TC;
	}
	
	public void setAssignedDollarsUnsplit_TC(BigDecimal assignedDollarsUnsplit_TC) {
		this.assignedDollarsUnsplit_TC = assignedDollarsUnsplit_TC;
	}
	
	public BigDecimal getAssignedDollarsSplit_IP() {
		return assignedDollarsSplit_IP;
	}

	public void setAssignedDollarsSplit_IP(BigDecimal assignedDollarsSplit_IP) {
		this.assignedDollarsSplit_IP = assignedDollarsSplit_IP;
	}

	public BigDecimal getAssignedDollarsUnsplit_IP() {
		return assignedDollarsUnsplit_IP;
	}

	public void setAssignedDollarsUnsplit_IP(BigDecimal assignedDollarsUnsplit_IP) {
		this.assignedDollarsUnsplit_IP = assignedDollarsUnsplit_IP;
	}

	public BigDecimal getAssignedDollarsSplit_IP_T() {
		return assignedDollarsSplit_IP_T;
	}

	public void setAssignedDollarsSplit_IP_T(BigDecimal assignedDollarsSplit_IP_T) {
		this.assignedDollarsSplit_IP_T = assignedDollarsSplit_IP_T;
	}

	public BigDecimal getAssignedDollarsSplit_IP_C() {
		return assignedDollarsSplit_IP_C;
	}

	public void setAssignedDollarsSplit_IP_C(BigDecimal assignedDollarsSplit_IP_C) {
		this.assignedDollarsSplit_IP_C = assignedDollarsSplit_IP_C;
	}

	public BigDecimal getAssignedDollarsSplit_IP_TC() {
		return assignedDollarsSplit_IP_TC;
	}

	public void setAssignedDollarsSplit_IP_TC(BigDecimal assignedDollarsSplit_IP_TC) {
		this.assignedDollarsSplit_IP_TC = assignedDollarsSplit_IP_TC;
	}

	public BigDecimal getAssignedDollarsUnsplit_IP_T() {
		return assignedDollarsUnsplit_IP_T;
	}

	public void setAssignedDollarsUnsplit_IP_T(
			BigDecimal assignedDollarsUnsplit_IP_T) {
		this.assignedDollarsUnsplit_IP_T = assignedDollarsUnsplit_IP_T;
	}

	public BigDecimal getAssignedDollarsUnsplit_IP_C() {
		return assignedDollarsUnsplit_IP_C;
	}

	public void setAssignedDollarsUnsplit_IP_C(
			BigDecimal assignedDollarsUnsplit_IP_C) {
		this.assignedDollarsUnsplit_IP_C = assignedDollarsUnsplit_IP_C;
	}

	public BigDecimal getAssignedDollarsUnsplit_IP_TC() {
		return assignedDollarsUnsplit_IP_TC;
	}

	public void setAssignedDollarsUnsplit_IP_TC(
			BigDecimal assignedDollarsUnsplit_IP_TC) {
		this.assignedDollarsUnsplit_IP_TC = assignedDollarsUnsplit_IP_TC;
	}

	public BigDecimal getAssignedDollarsSplit_OP() {
		return assignedDollarsSplit_OP;
	}

	public void setAssignedDollarsSplit_OP(BigDecimal assignedDollarsSplit_OP) {
		this.assignedDollarsSplit_OP = assignedDollarsSplit_OP;
	}

	public BigDecimal getAssignedDollarsUnsplit_OP() {
		return assignedDollarsUnsplit_OP;
	}

	public void setAssignedDollarsUnsplit_OP(BigDecimal assignedDollarsUnsplit_OP) {
		this.assignedDollarsUnsplit_OP = assignedDollarsUnsplit_OP;
	}
	
	public BigDecimal getAssignedDollarsSplit_OP_T() {
		return assignedDollarsSplit_OP_T;
	}

	public void setAssignedDollarsSplit_OP_T(BigDecimal assignedDollarsSplit_OP_T) {
		this.assignedDollarsSplit_OP_T = assignedDollarsSplit_OP_T;
	}

	public BigDecimal getAssignedDollarsSplit_OP_C() {
		return assignedDollarsSplit_OP_C;
	}

	public void setAssignedDollarsSplit_OP_C(BigDecimal assignedDollarsSplit_OP_C) {
		this.assignedDollarsSplit_OP_C = assignedDollarsSplit_OP_C;
	}
	
	public BigDecimal getAssignedDollarsSplit_OP_TC() {
		return assignedDollarsSplit_OP_TC;
	}

	public void setAssignedDollarsSplit_OP_TC(BigDecimal assignedDollarsSplit_OP_TC) {
		this.assignedDollarsSplit_OP_TC = assignedDollarsSplit_OP_TC;
	}

	public BigDecimal getAssignedDollarsUnsplit_OP_T() {
		return assignedDollarsUnsplit_OP_T;
	}

	public void setAssignedDollarsUnsplit_OP_T(
			BigDecimal assignedDollarsUnsplit_OP_T) {
		this.assignedDollarsUnsplit_OP_T = assignedDollarsUnsplit_OP_T;
	}

	public BigDecimal getAssignedDollarsUnsplit_OP_C() {
		return assignedDollarsUnsplit_OP_C;
	}

	public void setAssignedDollarsUnsplit_OP_C(
			BigDecimal assignedDollarsUnsplit_OP_C) {
		this.assignedDollarsUnsplit_OP_C = assignedDollarsUnsplit_OP_C;
	}

	public BigDecimal getAssignedDollarsUnsplit_OP_TC() {
		return assignedDollarsUnsplit_OP_TC;
	}

	public void setAssignedDollarsUnsplit_OP_TC(
			BigDecimal assignedDollarsUnsplit_OP_TC) {
		this.assignedDollarsUnsplit_OP_TC = assignedDollarsUnsplit_OP_TC;
	}

	public BigDecimal getAssignedDollarsSplit_PB() {
		return assignedDollarsSplit_PB;
	}

	public void setAssignedDollarsSplit_PB(BigDecimal assignedDollarsSplit_PB) {
		this.assignedDollarsSplit_PB = assignedDollarsSplit_PB;
	}

	public BigDecimal getAssignedDollarsUnsplit_PB() {
		return assignedDollarsUnsplit_PB;
	}

	public void setAssignedDollarsUnsplit_PB(BigDecimal assignedDollarsUnsplit_PB) {
		this.assignedDollarsUnsplit_PB = assignedDollarsUnsplit_PB;
	}
	
	public BigDecimal getAssignedDollarsSplit_PB_T() {
		return assignedDollarsSplit_PB_T;
	}

	public void setAssignedDollarsSplit_PB_T(BigDecimal assignedDollarsSplit_PB_T) {
		this.assignedDollarsSplit_PB_T = assignedDollarsSplit_PB_T;
	}

	public BigDecimal getAssignedDollarsSplit_PB_C() {
		return assignedDollarsSplit_PB_C;
	}

	public void setAssignedDollarsSplit_PB_C(BigDecimal assignedDollarsSplit_PB_C) {
		this.assignedDollarsSplit_PB_C = assignedDollarsSplit_PB_C;
	}

	public BigDecimal getAssignedDollarsSplit_PB_TC() {
		return assignedDollarsSplit_PB_TC;
	}

	public void setAssignedDollarsSplit_PB_TC(BigDecimal assignedDollarsSplit_PB_TC) {
		this.assignedDollarsSplit_PB_TC = assignedDollarsSplit_PB_TC;
	}

	public BigDecimal getAssignedDollarsUnsplit_PB_T() {
		return assignedDollarsUnsplit_PB_T;
	}

	public void setAssignedDollarsUnsplit_PB_T(
			BigDecimal assignedDollarsUnsplit_PB_T) {
		this.assignedDollarsUnsplit_PB_T = assignedDollarsUnsplit_PB_T;
	}

	public BigDecimal getAssignedDollarsUnsplit_PB_C() {
		return assignedDollarsUnsplit_PB_C;
	}

	public void setAssignedDollarsUnsplit_PB_C(
			BigDecimal assignedDollarsUnsplit_PB_C) {
		this.assignedDollarsUnsplit_PB_C = assignedDollarsUnsplit_PB_C;
	}

	public BigDecimal getAssignedDollarsUnsplit_PB_TC() {
		return assignedDollarsUnsplit_PB_TC;
	}

	public void setAssignedDollarsUnsplit_PB_TC(
			BigDecimal assignedDollarsUnsplit_PB_TC) {
		this.assignedDollarsUnsplit_PB_TC = assignedDollarsUnsplit_PB_TC;
	}

	public BigDecimal getAssignedDollarsSplit_RX() {
		return assignedDollarsSplit_RX;
	}

	public void setAssignedDollarsSplit_RX(BigDecimal assignedDollarsSplit_RX) {
		this.assignedDollarsSplit_RX = assignedDollarsSplit_RX;
	}

	public BigDecimal getAssignedDollarsUnsplit_RX() {
		return assignedDollarsUnsplit_RX;
	}

	public void setAssignedDollarsUnsplit_RX(BigDecimal assignedDollarsUnsplit_RX) {
		this.assignedDollarsUnsplit_RX = assignedDollarsUnsplit_RX;
	}

	public BigDecimal getAssignedDollarsSplit_RX_T() {
		return assignedDollarsSplit_RX_T;
	}

	public void setAssignedDollarsSplit_RX_T(BigDecimal assignedDollarsSplit_RX_T) {
		this.assignedDollarsSplit_RX_T = assignedDollarsSplit_RX_T;
	}

	public BigDecimal getAssignedDollarsSplit_RX_C() {
		return assignedDollarsSplit_RX_C;
	}

	public void setAssignedDollarsSplit_RX_C(BigDecimal assignedDollarsSplit_RX_C) {
		this.assignedDollarsSplit_RX_C = assignedDollarsSplit_RX_C;
	}

	public BigDecimal getAssignedDollarsUnsplit_RX_T() {
		return assignedDollarsUnsplit_RX_T;
	}

	public void setAssignedDollarsUnsplit_RX_T(
			BigDecimal assignedDollarsUnsplit_RX_T) {
		this.assignedDollarsUnsplit_RX_T = assignedDollarsUnsplit_RX_T;
	}

	public BigDecimal getAssignedDollarsUnsplit_RX_C() {
		return assignedDollarsUnsplit_RX_C;
	}

	public void setAssignedDollarsUnsplit_RX_C(
			BigDecimal assignedDollarsUnsplit_RX_C) {
		this.assignedDollarsUnsplit_RX_C = assignedDollarsUnsplit_RX_C;
	}

	public BigDecimal getAssociatedDollarsSplit_T() {
		return associatedDollarsSplit_T;
	}

	public void setAssociatedDollarsSplit_T(BigDecimal associatedDollarsSplit_T) {
		this.associatedDollarsSplit_T = associatedDollarsSplit_T;
	}

	public BigDecimal getAssociatedDollarsSplit_C() {
		return associatedDollarsSplit_C;
	}

	public void setAssociatedDollarsSplit_C(BigDecimal associatedDollarsSplit_C) {
		this.associatedDollarsSplit_C = associatedDollarsSplit_C;
	}

	public BigDecimal getAssociatedDollarsUnsplit_T() {
		return associatedDollarsUnsplit_T;
	}

	public void setAssociatedDollarsUnsplit_T(BigDecimal associatedDollarsUnsplit_T) {
		this.associatedDollarsUnsplit_T = associatedDollarsUnsplit_T;
	}

	public BigDecimal getAssociatedDollarsUnsplit_C() {
		return associatedDollarsUnsplit_C;
	}

	public void setAssociatedDollarsUnsplit_C(BigDecimal associatedDollarsUnsplit_C) {
		this.associatedDollarsUnsplit_C = associatedDollarsUnsplit_C;
	}



	public BigDecimal getAssociatedDollarsSplit_IP() {
		return associatedDollarsSplit_IP;
	}



	public void setAssociatedDollarsSplit_IP(BigDecimal associatedDollarsSplit_IP) {
		this.associatedDollarsSplit_IP = associatedDollarsSplit_IP;
	}



	public BigDecimal getAssociatedDollarsUnsplit_IP() {
		return associatedDollarsUnsplit_IP;
	}



	public void setAssociatedDollarsUnsplit_IP(
			BigDecimal associatedDollarsUnsplit_IP) {
		this.associatedDollarsUnsplit_IP = associatedDollarsUnsplit_IP;
	}



	public BigDecimal getAssociatedDollarsSplit_IP_T() {
		return associatedDollarsSplit_IP_T;
	}



	public void setAssociatedDollarsSplit_IP_T(
			BigDecimal associatedDollarsSplit_IP_T) {
		this.associatedDollarsSplit_IP_T = associatedDollarsSplit_IP_T;
	}



	public BigDecimal getAssociatedDollarsSplit_IP_C() {
		return associatedDollarsSplit_IP_C;
	}



	public void setAssociatedDollarsSplit_IP_C(
			BigDecimal associatedDollarsSplit_IP_C) {
		this.associatedDollarsSplit_IP_C = associatedDollarsSplit_IP_C;
	}



	public BigDecimal getAssociatedDollarsUnsplit_IP_T() {
		return associatedDollarsUnsplit_IP_T;
	}



	public void setAssociatedDollarsUnsplit_IP_T(
			BigDecimal associatedDollarsUnsplit_IP_T) {
		this.associatedDollarsUnsplit_IP_T = associatedDollarsUnsplit_IP_T;
	}



	public BigDecimal getAssociatedDollarsUnsplit_IP_C() {
		return associatedDollarsUnsplit_IP_C;
	}



	public void setAssociatedDollarsUnsplit_IP_C(
			BigDecimal associatedDollarsUnsplit_IP_C) {
		this.associatedDollarsUnsplit_IP_C = associatedDollarsUnsplit_IP_C;
	}



	public BigDecimal getAssociatedDollarsSplit_OP() {
		return associatedDollarsSplit_OP;
	}



	public void setAssociatedDollarsSplit_OP(BigDecimal associatedDollarsSplit_OP) {
		this.associatedDollarsSplit_OP = associatedDollarsSplit_OP;
	}



	public BigDecimal getAssociatedDollarsUnsplit_OP() {
		return associatedDollarsUnsplit_OP;
	}



	public void setAssociatedDollarsUnsplit_OP(
			BigDecimal associatedDollarsUnsplit_OP) {
		this.associatedDollarsUnsplit_OP = associatedDollarsUnsplit_OP;
	}



	public BigDecimal getAssociatedDollarsSplit_OP_T() {
		return associatedDollarsSplit_OP_T;
	}



	public void setAssociatedDollarsSplit_OP_T(
			BigDecimal associatedDollarsSplit_OP_T) {
		this.associatedDollarsSplit_OP_T = associatedDollarsSplit_OP_T;
	}



	public BigDecimal getAssociatedDollarsSplit_OP_C() {
		return associatedDollarsSplit_OP_C;
	}



	public void setAssociatedDollarsSplit_OP_C(
			BigDecimal associatedDollarsSplit_OP_C) {
		this.associatedDollarsSplit_OP_C = associatedDollarsSplit_OP_C;
	}



	public BigDecimal getAssociatedDollarsUnsplit_OP_T() {
		return associatedDollarsUnsplit_OP_T;
	}



	public void setAssociatedDollarsUnsplit_OP_T(
			BigDecimal associatedDollarsUnsplit_OP_T) {
		this.associatedDollarsUnsplit_OP_T = associatedDollarsUnsplit_OP_T;
	}



	public BigDecimal getAssociatedDollarsUnsplit_OP_C() {
		return associatedDollarsUnsplit_OP_C;
	}



	public void setAssociatedDollarsUnsplit_OP_C(
			BigDecimal associatedDollarsUnsplit_OP_C) {
		this.associatedDollarsUnsplit_OP_C = associatedDollarsUnsplit_OP_C;
	}



	public BigDecimal getAssociatedDollarsSplit_PB() {
		return associatedDollarsSplit_PB;
	}



	public void setAssociatedDollarsSplit_PB(BigDecimal associatedDollarsSplit_PB) {
		this.associatedDollarsSplit_PB = associatedDollarsSplit_PB;
	}



	public BigDecimal getAssociatedDollarsUnsplit_PB() {
		return associatedDollarsUnsplit_PB;
	}



	public void setAssociatedDollarsUnsplit_PB(
			BigDecimal associatedDollarsUnsplit_PB) {
		this.associatedDollarsUnsplit_PB = associatedDollarsUnsplit_PB;
	}



	public BigDecimal getAssociatedDollarsSplit_PB_T() {
		return associatedDollarsSplit_PB_T;
	}



	public void setAssociatedDollarsSplit_PB_T(
			BigDecimal associatedDollarsSplit_PB_T) {
		this.associatedDollarsSplit_PB_T = associatedDollarsSplit_PB_T;
	}



	public BigDecimal getAssociatedDollarsSplit_PB_C() {
		return associatedDollarsSplit_PB_C;
	}



	public void setAssociatedDollarsSplit_PB_C(
			BigDecimal associatedDollarsSplit_PB_C) {
		this.associatedDollarsSplit_PB_C = associatedDollarsSplit_PB_C;
	}



	public BigDecimal getAssociatedDollarsUnsplit_PB_T() {
		return associatedDollarsUnsplit_PB_T;
	}



	public void setAssociatedDollarsUnsplit_PB_T(
			BigDecimal associatedDollarsUnsplit_PB_T) {
		this.associatedDollarsUnsplit_PB_T = associatedDollarsUnsplit_PB_T;
	}



	public BigDecimal getAssociatedDollarsUnsplit_PB_C() {
		return associatedDollarsUnsplit_PB_C;
	}



	public void setAssociatedDollarsUnsplit_PB_C(
			BigDecimal associatedDollarsUnsplit_PB_C) {
		this.associatedDollarsUnsplit_PB_C = associatedDollarsUnsplit_PB_C;
	}



	public BigDecimal getAssociatedDollarsSplit_RX() {
		return associatedDollarsSplit_RX;
	}



	public void setAssociatedDollarsSplit_RX(BigDecimal associatedDollarsSplit_RX) {
		this.associatedDollarsSplit_RX = associatedDollarsSplit_RX;
	}



	public BigDecimal getAssociatedDollarsUnsplit_RX() {
		return associatedDollarsUnsplit_RX;
	}



	public void setAssociatedDollarsUnsplit_RX(
			BigDecimal associatedDollarsUnsplit_RX) {
		this.associatedDollarsUnsplit_RX = associatedDollarsUnsplit_RX;
	}



	public BigDecimal getAssociatedDollarsSplit_RX_T() {
		return associatedDollarsSplit_RX_T;
	}



	public void setAssociatedDollarsSplit_RX_T(
			BigDecimal associatedDollarsSplit_RX_T) {
		this.associatedDollarsSplit_RX_T = associatedDollarsSplit_RX_T;
	}



	public BigDecimal getAssociatedDollarsSplit_RX_C() {
		return associatedDollarsSplit_RX_C;
	}



	public void setAssociatedDollarsSplit_RX_C(
			BigDecimal associatedDollarsSplit_RX_C) {
		this.associatedDollarsSplit_RX_C = associatedDollarsSplit_RX_C;
	}



	public BigDecimal getAssociatedDollarsUnsplit_RX_T() {
		return associatedDollarsUnsplit_RX_T;
	}



	public void setAssociatedDollarsUnsplit_RX_T(
			BigDecimal associatedDollarsUnsplit_RX_T) {
		this.associatedDollarsUnsplit_RX_T = associatedDollarsUnsplit_RX_T;
	}



	public BigDecimal getAssociatedDollarsUnsplit_RX_C() {
		return associatedDollarsUnsplit_RX_C;
	}



	public void setAssociatedDollarsUnsplit_RX_C(
			BigDecimal associatedDollarsUnsplit_RX_C) {
		this.associatedDollarsUnsplit_RX_C = associatedDollarsUnsplit_RX_C;
	}


*/
	public HashMap<String, HashMap<String, HashMap<String, BigDecimal>>> getAssociatedDollarsByLevel() {
		return associatedDollarsByLevel;
	}


/*
	public void setAssociatedDollarsByLevel(
			HashMap<String, HashMap<String, HashMap<String, BigDecimal>>> associatedDollarsByLevel) {
		this.associatedDollarsByLevel = associatedDollarsByLevel;
	}
*/
	@SuppressWarnings("unused")
	private static org.apache.log4j.Logger log = Logger.getLogger(EpisodeShell.class);
	
}
